# Generated by Django 5.2.3 on 2025-06-12 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('foto_evento', models.FileField(blank=True, null=True, upload_to='eventos/fotos')),
                ('pdf_programa', models.FileField(blank=True, null=True, upload_to='eventos/programas')),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('industria', models.CharField(max_length=200)),
                ('logo_patrocinador', models.FileField(blank=True, null=True, upload_to='patrocinadores/logos')),
            ],
        ),
        migrations.CreateModel(
            name='EventoPatrocinador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aporte_economico', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pdf_contrato', models.FileField(blank=True, null=True, upload_to='eventos/contratos')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.evento')),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eventos.patrocinador')),
            ],
        ),
    ]
